# Generated by Django 4.2.8 on 2023-12-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0005_alter_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
